/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.5/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  `kotlin-dsl`
}

group = "org.arindom.takenotes"


dependencies {
  compileOnly(libs.android.gradlePlugin)
  compileOnly(libs.kotlin.gradlePlugin)
}

gradlePlugin {
  // Define the plugin
  plugins {
    register("application") {
      id = "org.arindom.takenotes.application"
      implementationClass = "org.arindom.takenotes.AndroidApplicationConvention"
    }
    register("composeLibrary") {
      id = "org.arindom.takenotes.compose.library"
      implementationClass = "org.arindom.takenotes.AndroidComposeLibraryConvention"
    }
    register("kmpLibrary"){
      id = "org.arindom.takenotes.kmp.library"
      implementationClass = "org.arindom.takenotes.KmpLibraryConvention"
    }

    register("koinPlugin"){
      id = "org.arindom.takenotes.koin"
      implementationClass = "org.arindom.takenotes.KoinConvention"
    }

    register("voyagerPlugin"){
      id = "org.arindom.takenotes.voyager"
      implementationClass = "org.arindom.takenotes.VoyagerConvention"
    }
  }
}
